### ISSUE TITLE
Panicking on Rust 1.50.0+

### ISSUE THREAD

**Issue by dtmelt** [twitu/rboids#5]
I found this project through the great series of blog posts, but unfortunately due to three-rs's dependency on the out-of-date package 'glutin', it will panic if you mouseover the view window when built on any version of Rust more recent than at least 1.50.0 (the most recent I have tested).

https://github.com/three-rs/three/issues/242

In conversation with the author via Reddit, it seems Rust 1.45 is the version used to build this project. Instead of manually switching toolchain versions every time one wants to work on the project, rustup supports automatic per-project toolchain switching with the "rust-toolchain" or "rust-toolchain.toml" configuration file placed in the project root: 

https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file

I was able to get this working with the following contents for my rust-toolchain.toml:

```
[toolchain]     
channel = "1.45"
```

**Comment by twitu** [comment]
Thanks a lot for sharing this critical issue and also proposing an elegant fix for it. I've added the `rust-toolchain.toml` file to the repository.
